### ISSUE TITLE
wearGPT 2.0 API key

### ISSUE THREAD

**Issue by Pici60** [AnujMutha/WearGPT#2]
Saját APi kulcsot kér a wearGPT 2.0! Hogyan lehet generálni az alkalmazáshoz?

**Comment by AnujMutha** [comment]
> Saját APi kulcsot kér a wearGPT 2.0! Hogyan lehet generálni az alkalmazáshoz?

Hey

In order to generate your own Api key, follow the below step.

1. Head over to openAI website and create an account and proceed with login.
2. Click on "view api keys" under personal tab.
3. click on "create new secret key"
4. done, you now have your own api key.
5. enter this api key in your watch in the api key section in the app's settings.

Hope this helps !

Thanks.

**Comment by Pici60** [comment]
Dear developer!

Thank you very much for your help, it was solved!


 Sincerely, Sándor Bakó

A N U J M U T H A ***@***.***> ezt írta (időpont: 2023. márc.
31., Pén 9:15):
