### ISSUE TITLE
No responses

### ISSUE THREAD

**Issue by exitido** [AnujMutha/WearGPT#6]
Ticwatch pro 3 ultra

Valid API

When i send question:

Thinking...
Response appears here...

I dont have any response

**Comment by AnujMutha** [comment]
Hey,

I would like to inform you that the api works on the credit and i think the credits which are given by OPENAI for your account has been exhausted due to which app is not responding to you queries.


Head over to "view api usage" section on OpenAI Website and view remaining credits count.


If it's zero that means you have used all your free credits and you will need to buy them from OpenAI itself.



Also, certain times the openAi themselves never gives out free credits for some accounts fyi. In these cases, you would need to buy the credits.


Remember, It's OpenAI which requires charges to use their API, my app was totally FREE and still it is free to use at any point of time.


I hope i was able to help you
