### ISSUE TITLE
Api key installed and Version 2.0 no response

### ISSUE THREAD

**Issue by Chefschweisser** [AnujMutha/WearGPT#8]
I installed everything and the key but i get no response from gpt.It says thinking for a second but then nothing happens.Servers are on cuz i can ask it via mobile.

**Comment by AnujMutha** [comment]
> I installed everything and the key but i get no response from gpt.It says thinking for a second but then nothing happens.Servers are on cuz i can ask it via mobile.

I think the credits which are given by OPENAI for your account has been exhausted due to which app is not responding to you queries anymore.

Head over to "view api usage" section on OpenAI Website and view remaining credits count.

If it's zero that means you have used all your free credits or they might have been expired and you will need to buy them from OpenAI itself.

Also, certain times the account never gives out free credits for some accounts fyi. In these cases, you would need to buy the credits.

Remember, It's OpenAI which requires charges to use their API, my app was totally FREE and still it is free to use at any point of time.

I hope i was able to help you
